services:
  - type: web
    name: cybermind-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: HF_KEYS
        sync: false
      - key: NVIDIA_KEYS
        sync: false
      - key: BYTEZ_KEYS
        sync: false
      - key: OPENROUTER_KEYS
        sync: false
